server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Url of our Keycloak instance
          issuer-uri: http://localhost:8080/realms/demo
          # Url to validate JWT
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: demo-rest-api
      principle-attribute: preferred_username
